# version: '3.1'

services:
  
  countit:
    build: .
    image: 'k3nny0r/countit'
    container_name: 'countit'
    #volumes:
    #  - ./data:/app/data_metrics
    env_file:
      - ./countit.env
    ports:
      - '127.0.0.1:5050:5050'
    restart: unless-stopped
